/**
 * WedFlow Static Template Library (Phase 2)
 *
 * Comprehensive, coherent planning sequences across:
 * - venue (7 steps)
 * - catering (7 steps)
 * - photography (7 steps)
 * - decoration (7 steps)
 * - makeup_attire (7 steps)
 * - invitation (7 steps)
 * - prosesi_administrasi (7 steps, conditional)
 * - general (7 steps)
 *
 * Principles:
 * - Pure static data.
 * - Sequence progression (1 -> 7).
 * - Relative window timing (days before wedding), not hardcoded calendar dates.
 * - Non-universal religious & legal administration.
 */

import { StarterTaskTemplate } from './templateTypes';

export const STARTER_TASK_TEMPLATES: StarterTaskTemplate[] = [
  // ── VENUE & GEDUNG ────────────────────────────────────────────────────────
  {
    id: 'venue-1-needs',
    category: 'venue',
    title: 'Tentukan kebutuhan venue',
    description: 'Diskusikan jenis acara, perkiraan kapasitas ruangan, dan akses lokasi yang dibutuhkan.',
    sequence: 1,
    applicableEvents: ['ceremony', 'reception', 'cultural'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 240, maxDaysBeforeWedding: 365 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 60,
  },
  {
    id: 'venue-2-criteria',
    category: 'venue',
    title: 'Tentukan kriteria venue',
    description: 'Tetapkan preferensi indoor/outdoor, fasilitas parkir, ketersediaan ruang rias, dan kebijakan vendor.',
    sequence: 2,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 210, maxDaysBeforeWedding: 365 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['venue-1-needs'],
    estimatedMinutes: 45,
  },
  {
    id: 'venue-3-shortlist',
    category: 'venue',
    title: 'Buat shortlist venue',
    description: 'Kumpulkan minimal 3–5 opsi venue yang sesuai kriteria dan rentang anggaran.',
    sequence: 3,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 180, maxDaysBeforeWedding: 330 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['venue-2-criteria'],
    estimatedMinutes: 90,
  },
  {
    id: 'venue-4-compare',
    category: 'venue',
    title: 'Bandingkan pilihan venue',
    description: 'Bandingkan paket biaya, benefit, jam pemakaian, dan ketentuan overtime masing-masing venue.',
    sequence: 4,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 300 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['venue-3-shortlist'],
    estimatedMinutes: 60,
  },
  {
    id: 'venue-5-survey',
    category: 'venue',
    title: 'Survey / cek venue',
    description: 'Jadwalkan kunjungan langsung ke lokasi untuk memastikan kondisi ruangan, pencahayaan, dan aksesibilitas.',
    sequence: 5,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['venue-4-compare'],
    estimatedMinutes: 120,
  },
  {
    id: 'venue-6-select',
    category: 'venue',
    title: 'Pilih venue',
    description: 'Tentukan pilihan venue terbaik bersama pasangan dan konfirmasi ketersediaan tanggal acara.',
    sequence: 6,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['venue-5-survey'],
    estimatedMinutes: 45,
  },
  {
    id: 'venue-7-booking',
    category: 'venue',
    title: 'Booking / amankan venue',
    description: 'Tanda tangani kontrak pemesanan venue dan bayarkan uang muka (DP) sesuai kesepakatan.',
    sequence: 7,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['venue-6-select'],
    estimatedMinutes: 60,
  },

  // ── CATERING ──────────────────────────────────────────────────────────────
  {
    id: 'catering-1-needs',
    category: 'catering',
    title: 'Tentukan kebutuhan catering',
    description: 'Tentukan format jamuan makan (buffet, gubukan, plated) dan preferensi menu keluarga.',
    sequence: 1,
    applicableEvents: ['reception', 'family', 'other'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 210, maxDaysBeforeWedding: 330 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 45,
  },
  {
    id: 'catering-2-estimate',
    category: 'catering',
    title: 'Tentukan estimasi jumlah porsi',
    description: 'Hitung rasio porsi makanan berdasarkan estimasi jumlah undangan dan rasio pendamping.',
    sequence: 2,
    applicableEvents: ['reception', 'family'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 180, maxDaysBeforeWedding: 300 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['catering-1-needs'],
    estimatedMinutes: 45,
  },
  {
    id: 'catering-3-search',
    category: 'catering',
    title: 'Cari vendor catering',
    description: 'Kumpulkan rekomendasi vendor catering rekanan venue atau catering independen bereputasi baik.',
    sequence: 3,
    applicableEvents: ['reception', 'family'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['catering-2-estimate'],
    estimatedMinutes: 60,
  },
  {
    id: 'catering-4-compare',
    category: 'catering',
    title: 'Bandingkan paket & harga',
    description: 'Bandingkan rincian menu, bonus gubukan, layanan pelayan, dan biaya servis per vendor.',
    sequence: 4,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['catering-3-search'],
    estimatedMinutes: 60,
  },
  {
    id: 'catering-5-menu',
    category: 'catering',
    title: 'Cek menu & layanan',
    description: 'Ikuti food tasting atau uji rasa menu utama dan pastikan standar kebersihan serta penyajian.',
    sequence: 5,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 210 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['catering-4-compare'],
    estimatedMinutes: 90,
  },
  {
    id: 'catering-6-negotiate',
    category: 'catering',
    title: 'Negosiasi paket catering',
    description: 'Diskusikan penyesuaian menu, tambahan porsi bonus, dan jadwal pengiriman ke lokasi.',
    sequence: 6,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['catering-5-menu'],
    estimatedMinutes: 45,
  },
  {
    id: 'catering-7-booking',
    category: 'catering',
    title: 'Booking / amankan catering',
    description: 'Finalisasi pesanan menu dengan kontrak resmi dan lakukan pembayaran DP.',
    sequence: 7,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 180 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['catering-6-negotiate'],
    estimatedMinutes: 45,
  },

  // ── FOTO & VIDEO ──────────────────────────────────────────────────────────
  {
    id: 'photo-1-needs',
    category: 'photography',
    title: 'Tentukan kebutuhan dokumentasi',
    description: 'Tentukan ruang lingkup liputan: pre-wedding, akad/pemberkatan, resepsi, atau rangkaian acara keluarga.',
    sequence: 1,
    applicableEvents: ['ceremony', 'reception', 'cultural'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 180, maxDaysBeforeWedding: 300 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 45,
  },
  {
    id: 'photo-2-search',
    category: 'photography',
    title: 'Cari vendor foto & video',
    description: 'Eksplorasi fotografer dan videografer yang memiliki gaya visual (tone, mood, candid/editorial) yang kamu sukai.',
    sequence: 2,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['photo-1-needs'],
    estimatedMinutes: 60,
  },
  {
    id: 'photo-3-shortlist',
    category: 'photography',
    title: 'Buat shortlist vendor',
    description: 'Pilih 3–4 vendor dokumentasi dengan portofolio terbaik dan sesuaikan dengan alokasi budget.',
    sequence: 3,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['photo-2-search'],
    estimatedMinutes: 60,
  },
  {
    id: 'photo-4-compare',
    category: 'photography',
    title: 'Bandingkan portofolio & paket',
    description: 'Pelajari paket layanan: jumlah kru, durasi kerja, album fisik, video teaser, dan raw footage.',
    sequence: 4,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 210 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['photo-3-shortlist'],
    estimatedMinutes: 45,
  },
  {
    id: 'photo-5-contact',
    category: 'photography',
    title: 'Hubungi vendor pilihan',
    description: 'Cek ketersediaan tanggal dan diskusikan ekspektasi hasil foto/video dengan vendor.',
    sequence: 5,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['photo-4-compare'],
    estimatedMinutes: 45,
  },
  {
    id: 'photo-6-negotiate',
    category: 'photography',
    title: 'Negosiasi & pilih vendor',
    description: 'Sepakati rincian hak serah terima file, estimasi waktu editing, dan termin pembayaran.',
    sequence: 6,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 150 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['photo-5-contact'],
    estimatedMinutes: 45,
  },
  {
    id: 'photo-7-booking',
    category: 'photography',
    title: 'Booking / amankan foto & video',
    description: 'Kunci jadwal fotografer & videografer dengan surat perjanjian kerja dan DP.',
    sequence: 7,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 150 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['photo-6-negotiate'],
    estimatedMinutes: 45,
  },

  // ── DEKORASI ──────────────────────────────────────────────────────────────
  {
    id: 'decoration-1-concept',
    category: 'decoration',
    title: 'Tentukan konsep dekorasi',
    description: 'Pilih tema dekorasi utama (tradisional, modern, minimalis, botanical, atau perpaduan tema).',
    sequence: 1,
    applicableEvents: ['ceremony', 'reception', 'cultural'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: [],
    estimatedMinutes: 45,
  },
  {
    id: 'decoration-2-references',
    category: 'decoration',
    title: 'Kumpulkan referensi dekorasi',
    description: 'Kumpulkan inspirasi pelaminan, area penerima tamu, backdrop akad, dan pencahayaan panggung.',
    sequence: 2,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'medium',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['decoration-1-concept'],
    estimatedMinutes: 60,
  },
  {
    id: 'decoration-3-needs',
    category: 'decoration',
    title: 'Tentukan kebutuhan dekorasi',
    description: 'Buat daftar titik dekorasi wajib: pelaminan, lorong masuk, photo booth, dan meja keluarga.',
    sequence: 3,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 210 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['decoration-2-references'],
    estimatedMinutes: 45,
  },
  {
    id: 'decoration-4-search',
    category: 'decoration',
    title: 'Cari vendor dekorasi',
    description: 'Cari vendor dekorasi yang berpengalaman mengerjakan layout di venue yang telah kamu pilih.',
    sequence: 4,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['decoration-3-needs'],
    estimatedMinutes: 60,
  },
  {
    id: 'decoration-5-compare',
    category: 'decoration',
    title: 'Bandingkan portofolio & paket',
    description: 'Bandingkan portofolio pengerjaan asli (bukan hanya render 3D) dan rincian bunga segar vs artificial.',
    sequence: 5,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 150 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['decoration-4-search'],
    estimatedMinutes: 45,
  },
  {
    id: 'decoration-6-discuss',
    category: 'decoration',
    title: 'Diskusikan konsep dengan vendor',
    description: 'Lakukan konsultasi desain detail, pemilihan skema warna, dan tata letak pencahayaan (lighting).',
    sequence: 6,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 120 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['decoration-5-compare'],
    estimatedMinutes: 60,
  },
  {
    id: 'decoration-7-booking',
    category: 'decoration',
    title: 'Pilih & booking vendor dekorasi',
    description: 'Setujui sketsa/moodboard final dekorasi dan bayar tanda jadi (DP) pemesanan.',
    sequence: 7,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 120 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['decoration-6-discuss'],
    estimatedMinutes: 45,
  },

  // ── MUA & BUSANA ──────────────────────────────────────────────────────────
  {
    id: 'mua-1-needs',
    category: 'makeup_attire',
    title: 'Tentukan kebutuhan MUA & busana',
    description: 'Hitung kebutuhan rias dan busana untuk kedua mempelai, orang tua, dan pengiring pengantin.',
    sequence: 1,
    applicableEvents: ['ceremony', 'reception', 'cultural'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 45,
  },
  {
    id: 'mua-2-style',
    category: 'makeup_attire',
    title: 'Tentukan gaya / referensi',
    description: 'Pilih referensi riasan (flawless, bold, natural) dan gaya busana (adat tradisi, modern, internasional).',
    sequence: 2,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 240 },
    priority: 'medium',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['mua-1-needs'],
    estimatedMinutes: 45,
  },
  {
    id: 'mua-3-search-mua',
    category: 'makeup_attire',
    title: 'Cari vendor MUA',
    description: 'Cari makeup artist profesional dengan hasil riasan yang sesuai preferensi kulit dan bentuk wajah.',
    sequence: 3,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 210 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: ['mua-2-style'],
    estimatedMinutes: 60,
  },
  {
    id: 'mua-4-attire',
    category: 'makeup_attire',
    title: 'Cari / tentukan busana',
    description: 'Tentukan apakah busana pengantin akan sewa perdana, sewa biasa, atau jahit custom.',
    sequence: 4,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['mua-3-search-mua'],
    estimatedMinutes: 60,
  },
  {
    id: 'mua-5-compare',
    category: 'makeup_attire',
    title: 'Bandingkan paket & harga',
    description: 'Bandingkan paket bundle MUA + busana atau vendor terpisah termasuk aksesoris dan melati/veil.',
    sequence: 5,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 150 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['mua-4-attire'],
    estimatedMinutes: 45,
  },
  {
    id: 'mua-6-fitting',
    category: 'makeup_attire',
    title: 'Trial / fitting jika diperlukan',
    description: 'Lakukan uji coba makeup (jika ada) dan fitting ukuran pakaian pengantin agar pas di badan.',
    sequence: 6,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'optional',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 90 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['mua-5-compare'],
    estimatedMinutes: 120,
  },
  {
    id: 'mua-7-booking',
    category: 'makeup_attire',
    title: 'Booking / finalisasi MUA & busana',
    description: 'Amankan tanggal MUA dan kunci jadwal busana dengan tanda tangan kontrak dan DP.',
    sequence: 7,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 120 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['mua-5-compare'],
    estimatedMinutes: 45,
  },

  // ── UNDANGAN ──────────────────────────────────────────────────────────────
  {
    id: 'invitation-1-needs',
    category: 'invitation',
    title: 'Tentukan kebutuhan undangan',
    description: 'Tentukan rasio undangan fisik (cetak) dan undangan digital/website sesuai karakteristik tamu.',
    sequence: 1,
    applicableEvents: ['reception', 'ceremony'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 120, maxDaysBeforeWedding: 210 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: [],
    estimatedMinutes: 45,
  },
  {
    id: 'invitation-2-concept',
    category: 'invitation',
    title: 'Tentukan konsep & informasi undangan',
    description: 'Susun informasi penting: nama kedua mempelai & orang tua, waktu, lokasi, dresscode, dan peta.',
    sequence: 2,
    applicableEvents: ['reception', 'ceremony'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'medium',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['invitation-1-needs'],
    estimatedMinutes: 45,
  },
  {
    id: 'invitation-3-guestlist',
    category: 'invitation',
    title: 'Tentukan daftar penerima',
    description: 'Kompilasi daftar nama tamu dan nomor kontak untuk pengiriman undangan fisik dan digital.',
    sequence: 3,
    applicableEvents: ['reception', 'ceremony'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 75, maxDaysBeforeWedding: 150 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: ['invitation-2-concept'],
    estimatedMinutes: 90,
  },
  {
    id: 'invitation-4-vendor',
    category: 'invitation',
    title: 'Pilih format / vendor undangan',
    description: 'Pilih percetakan undangan cetak dan platform undangan digital/website yang kamu percaya.',
    sequence: 4,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 120 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['invitation-3-guestlist'],
    estimatedMinutes: 45,
  },
  {
    id: 'invitation-5-design',
    category: 'invitation',
    title: 'Siapkan desain & konten',
    description: 'Proofread teks penulisan nama, gelar, waktu, dan tautan RSVP pada contoh preview undangan.',
    sequence: 5,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 90 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['invitation-4-vendor'],
    estimatedMinutes: 60,
  },
  {
    id: 'invitation-6-review',
    category: 'invitation',
    title: 'Review final undangan',
    description: 'Cek sample cetak fisik (dummy) atau tautan live undangan digital sebelum diproduksi massal.',
    sequence: 6,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 35, maxDaysBeforeWedding: 75 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['invitation-5-design'],
    estimatedMinutes: 30,
  },
  {
    id: 'invitation-7-distribute',
    category: 'invitation',
    title: 'Distribusikan undangan',
    description: 'Kirim undangan fisik dan sebar undangan digital kepada seluruh daftar tamu undangan.',
    sequence: 7,
    applicableEvents: ['reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 21, maxDaysBeforeWedding: 45 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['invitation-6-review'],
    estimatedMinutes: 120,
  },

  // ── PROSESI & ADMINISTRASI (CONDITIONAL) ───────────────────────────────────
  {
    id: 'prosesi-1-plan',
    category: 'prosesi_administrasi',
    title: 'Tentukan rangkaian prosesi yang akan dilakukan',
    description: 'Sepakati bersama pasangan dan keluarga urutan acara keagamaan, legal sipil, dan rangkaian tradisi.',
    sequence: 1,
    applicableEvents: ['ceremony', 'cultural', 'family'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 210 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 60,
  },
  {
    id: 'prosesi-2-coordination',
    category: 'prosesi_administrasi',
    title: 'Tentukan pihak yang perlu dikoordinasikan',
    description: 'Identifikasi saksi, pemandu adat, tokoh agama, atau pihak keluarga yang memegang peran kunci.',
    sequence: 2,
    applicableEvents: ['ceremony', 'cultural'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 75, maxDaysBeforeWedding: 180 },
    priority: 'medium',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['prosesi-1-plan'],
    estimatedMinutes: 45,
  },
  {
    id: 'prosesi-3-admin-needs',
    category: 'prosesi_administrasi',
    title: 'Identifikasi kebutuhan administrasi pernikahan',
    description: 'Cari tahu syarat dokumen pencatatan nikah (KUA/Disdukcapil/Rumah Ibadah) yang berlaku untuk situasimu.',
    sequence: 3,
    applicableEvents: ['ceremony'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 60, maxDaysBeforeWedding: 150 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: ['prosesi-2-coordination'],
    estimatedMinutes: 60,
  },
  {
    id: 'prosesi-4-docs',
    category: 'prosesi_administrasi',
    title: 'Siapkan daftar dokumen yang perlu dicek',
    description: 'Kumpulkan berkas identitas pribadi dan dokumen pendukung sesuai arahan instansi terkait.',
    sequence: 4,
    applicableEvents: ['ceremony'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 120 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['prosesi-3-admin-needs'],
    estimatedMinutes: 90,
  },
  {
    id: 'prosesi-5-confirm-procedure',
    category: 'prosesi_administrasi',
    title: 'Konfirmasi prosedur dengan instansi / pihak terkait',
    description: 'Pastikan jadwal pemeriksaan berkas dan kehadiran petugas resmi pada hari dan waktu acara.',
    sequence: 5,
    applicableEvents: ['ceremony'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 30, maxDaysBeforeWedding: 90 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['prosesi-4-docs'],
    estimatedMinutes: 45,
  },
  {
    id: 'prosesi-6-confirm-religious',
    category: 'prosesi_administrasi',
    title: 'Konfirmasi detail prosesi dengan pihak keagamaan/pemimpin upacara',
    description: 'Diskusikan susunan tata cara upacara, durasi, perlengkapan khusus, dan gladi resik singkat.',
    sequence: 6,
    applicableEvents: ['ceremony'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 21, maxDaysBeforeWedding: 60 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['prosesi-5-confirm-procedure'],
    estimatedMinutes: 60,
  },
  {
    id: 'prosesi-7-finalize',
    category: 'prosesi_administrasi',
    title: 'Finalisasi kebutuhan prosesi',
    description: 'Pastikan seluruh kelengkapan prosesi, mahar/cincin, dan dokumen legal siap pada H-1 acara.',
    sequence: 7,
    applicableEvents: ['ceremony', 'cultural'],
    applicability: 'conditional',
    recommendedWindow: { minDaysBeforeWedding: 7, maxDaysBeforeWedding: 30 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['prosesi-6-confirm-religious'],
    estimatedMinutes: 45,
  },

  // ── UMUM / GENERAL ────────────────────────────────────────────────────────
  {
    id: 'general-1-concept',
    category: 'general',
    title: 'Tentukan konsep & gaya pernikahan bersama pasangan',
    description: 'Samakan visi, batasan anggaran, dan suasana pernikahan yang diinginkan oleh kedua pihak.',
    sequence: 1,
    applicableEvents: ['ceremony', 'reception', 'family', 'other'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 240, maxDaysBeforeWedding: 365 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: [],
    estimatedMinutes: 60,
  },
  {
    id: 'general-2-budget',
    category: 'general',
    title: 'Susun estimasi alokasi anggaran utama',
    description: 'Tentukan plafon batas biaya tiap pos pengeluaran penting agar pengeluaran tetap terkontrol.',
    sequence: 2,
    applicableEvents: ['ceremony', 'reception', 'family', 'other'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 210, maxDaysBeforeWedding: 330 },
    priority: 'high',
    isStarterCandidate: true,
    isCatchUpCandidate: true,
    prerequisites: ['general-1-concept'],
    estimatedMinutes: 60,
  },
  {
    id: 'general-3-family',
    category: 'general',
    title: 'Bentuk panitia inti keluarga atau tim pendukung',
    description: 'Bicarakan pembentukan tim pelaksana dari pihak keluarga atau wedding planner independen.',
    sequence: 3,
    applicableEvents: ['ceremony', 'reception', 'family'],
    applicability: 'optional',
    recommendedWindow: { minDaysBeforeWedding: 150, maxDaysBeforeWedding: 270 },
    priority: 'medium',
    isStarterCandidate: true,
    isCatchUpCandidate: false,
    prerequisites: ['general-2-budget'],
    estimatedMinutes: 60,
  },
  {
    id: 'general-4-roles',
    category: 'general',
    title: 'Susun pembagian peran dan tanggung jawab',
    description: 'Tentukan penanggung jawab per pos: logistik, konsumsi keluarga, koordinasi vendor, dan keamanan.',
    sequence: 4,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'optional',
    recommendedWindow: { minDaysBeforeWedding: 90, maxDaysBeforeWedding: 180 },
    priority: 'medium',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['general-3-family'],
    estimatedMinutes: 45,
  },
  {
    id: 'general-5-logistics',
    category: 'general',
    title: 'Siapkan daftar perlengkapan dan logistik penting',
    description: 'Catat barang bawaan: kotak angpao, perlengkapan touch-up, cadangan pakaian, dan obat darurat.',
    sequence: 5,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 45, maxDaysBeforeWedding: 90 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: false,
    prerequisites: ['general-4-roles'],
    estimatedMinutes: 60,
  },
  {
    id: 'general-6-rundown',
    category: 'general',
    title: 'Susun alur koordinasi hari-H',
    description: 'Buat susunan waktu (rundown) dari sesi makeup, akad/pemberkatan, hingga penutupan resepsi.',
    sequence: 6,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 21, maxDaysBeforeWedding: 60 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['general-5-logistics'],
    estimatedMinutes: 90,
  },
  {
    id: 'general-7-briefing',
    category: 'general',
    title: 'Finalisasi rundown dan briefing tim',
    description: 'Adakan pertemuan teknis singkat (technical meeting) bersama seluruh vendor dan panitia keluarga.',
    sequence: 7,
    applicableEvents: ['ceremony', 'reception'],
    applicability: 'core',
    recommendedWindow: { minDaysBeforeWedding: 7, maxDaysBeforeWedding: 21 },
    priority: 'high',
    isStarterCandidate: false,
    isCatchUpCandidate: true,
    prerequisites: ['general-6-rundown'],
    estimatedMinutes: 120,
  },
];
