import { supabase } from '../lib/supabaseClient';
import { StoredWorkspace } from '../types/workspace';
import { CategoryId, PlanningPriority } from '../types/onboarding';
import {
  normalizeReligiousContexts,
  normalizeCulturalContext,
  ReligiousContext,
  CulturalContext,
} from '../domain/context';

export interface SupabaseWorkspaceRow {
  id: string;
  user_id: string;
  couple_name: string;
  wedding_date: string;
  estimated_budget: number | string;
  estimated_guest_count: number;
  primary_planning_priority: string;
  completed_categories: string[];
  religious_contexts?: ReligiousContext[] | null;
  cultural_context?: CulturalContext | null;
  created_at: string;
  updated_at: string;
}

export function mapRowToStoredWorkspace(row: SupabaseWorkspaceRow): StoredWorkspace {
  return {
    id: row.id,
    userId: row.user_id,
    coupleName: row.couple_name,
    weddingDate: row.wedding_date,
    estimatedBudget: Number(row.estimated_budget) || 100_000_000,
    estimatedGuestCount: Number(row.estimated_guest_count) || 400,
    completedCategories: (row.completed_categories as CategoryId[]) || [],
    primaryPlanningPriority: (row.primary_planning_priority as PlanningPriority) || 'checklist',
    religiousContexts: normalizeReligiousContexts(row.religious_contexts),
    culturalContext: normalizeCulturalContext(row.cultural_context),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function mapWorkspaceToRow(
  workspace: Partial<StoredWorkspace>,
  userId: string
): Partial<SupabaseWorkspaceRow> {
  const row: Partial<SupabaseWorkspaceRow> = {
    user_id: userId,
  };

  if (workspace.coupleName !== undefined) row.couple_name = workspace.coupleName;
  if (workspace.weddingDate !== undefined) row.wedding_date = workspace.weddingDate;
  if (workspace.estimatedBudget !== undefined) row.estimated_budget = workspace.estimatedBudget;
  if (workspace.estimatedGuestCount !== undefined) row.estimated_guest_count = workspace.estimatedGuestCount;
  if (workspace.primaryPlanningPriority !== undefined) row.primary_planning_priority = workspace.primaryPlanningPriority;
  if (workspace.completedCategories !== undefined) row.completed_categories = workspace.completedCategories;
  if (workspace.religiousContexts !== undefined) {
    row.religious_contexts = normalizeReligiousContexts(workspace.religiousContexts);
  }
  if (workspace.culturalContext !== undefined) {
    row.cultural_context = normalizeCulturalContext(workspace.culturalContext);
  }
  if (workspace.updatedAt !== undefined) row.updated_at = workspace.updatedAt;

  return row;
}

/**
 * Fetches the workspace for a given user ID from Supabase.
 * Returns null if no workspace exists for the user.
 */
export async function fetchWorkspaceByUserId(userId: string): Promise<StoredWorkspace | null> {
  if (!userId) {
    return null;
  }

  const { data, error } = await supabase
    .from('workspaces')
    .select('*')
    .eq('user_id', userId)
    .maybeSingle();

  if (error) {
    throw error;
  }

  if (!data) {
    return null;
  }

  return mapRowToStoredWorkspace(data as SupabaseWorkspaceRow);
}

/**
 * Inserts a new workspace in Supabase for the authenticated user.
 * ID is generated by the database (UUID).
 */
export async function insertWorkspace(
  data: Omit<StoredWorkspace, 'id' | 'createdAt' | 'updatedAt' | 'userId'>,
  userId: string
): Promise<StoredWorkspace> {
  if (!userId) {
    throw new Error('User ID is required to create a workspace in Supabase.');
  }

  const now = new Date().toISOString();
  const payload = {
    user_id: userId,
    couple_name: data.coupleName.trim() || 'Adit & Nisa',
    wedding_date: data.weddingDate,
    estimated_budget: data.estimatedBudget || 100_000_000,
    estimated_guest_count: data.estimatedGuestCount || 400,
    completed_categories: data.completedCategories || [],
    primary_planning_priority: data.primaryPlanningPriority || 'checklist',
    religious_contexts: normalizeReligiousContexts(data.religiousContexts),
    cultural_context: normalizeCulturalContext(data.culturalContext),
    created_at: now,
    updated_at: now,
  };

  let { data: inserted, error } = await supabase
    .from('workspaces')
    .insert(payload)
    .select('*')
    .single();

  // Graceful backward compatibility if context columns do not exist in live schema
  if (error && (error.code === 'PGRST204' || error.code === '42703')) {
    const basePayload = {
      user_id: userId,
      couple_name: payload.couple_name,
      wedding_date: payload.wedding_date,
      estimated_budget: payload.estimated_budget,
      estimated_guest_count: payload.estimated_guest_count,
      completed_categories: payload.completed_categories,
      primary_planning_priority: payload.primary_planning_priority,
      created_at: payload.created_at,
      updated_at: payload.updated_at,
    };
    const retry = await supabase
      .from('workspaces')
      .insert(basePayload)
      .select('*')
      .single();
    inserted = retry.data;
    error = retry.error;
  }

  if (error) {
    throw new Error(error.message || 'Gagal membuat workspace di database.');
  }

  return mapRowToStoredWorkspace(inserted as SupabaseWorkspaceRow);
}

/**
 * Updates an existing workspace in Supabase.
 */
export async function updateWorkspace(
  workspace: StoredWorkspace
): Promise<StoredWorkspace> {
  if (!workspace.id) {
    throw new Error('Workspace ID is required for update.');
  }

  const now = new Date().toISOString();
  const payload = {
    couple_name: workspace.coupleName,
    wedding_date: workspace.weddingDate,
    estimated_budget: workspace.estimatedBudget,
    estimated_guest_count: workspace.estimatedGuestCount,
    primary_planning_priority: workspace.primaryPlanningPriority,
    completed_categories: workspace.completedCategories,
    religious_contexts: normalizeReligiousContexts(workspace.religiousContexts),
    cultural_context: normalizeCulturalContext(workspace.culturalContext),
    updated_at: now,
  };

  let { data: updated, error } = await supabase
    .from('workspaces')
    .update(payload)
    .eq('id', workspace.id)
    .select('*')
    .single();

  // Graceful backward compatibility if context columns do not exist in live schema
  if (error && (error.code === 'PGRST204' || error.code === '42703')) {
    const basePayload = {
      couple_name: workspace.coupleName,
      wedding_date: workspace.weddingDate,
      estimated_budget: workspace.estimatedBudget,
      estimated_guest_count: workspace.estimatedGuestCount,
      primary_planning_priority: workspace.primaryPlanningPriority,
      completed_categories: workspace.completedCategories,
      updated_at: now,
    };
    const retry = await supabase
      .from('workspaces')
      .update(basePayload)
      .eq('id', workspace.id)
      .select('*')
      .single();
    updated = retry.data;
    error = retry.error;
  }

  if (error) {
    throw new Error(error.message || 'Gagal memperbarui workspace di database.');
  }

  return mapRowToStoredWorkspace(updated as SupabaseWorkspaceRow);
}

export interface ResetPlanningResult {
  success: boolean;
  workspace_id?: string;
  user_id?: string;
  message?: string;
  reset_at?: string;
}

/**
 * Invokes the atomic Supabase RPC `reset_user_wedding_planning`
 * to safely delete all child planning data and reset the workspace fields
 * while strictly preserving the workspace record, customer entitlements, orders, and payments.
 */
export async function resetPlanningDataInDb(): Promise<ResetPlanningResult> {
  const { data, error } = await supabase.rpc('reset_user_wedding_planning');

  if (error) {
    console.error('[WedFlow] Failed to reset planning data in Supabase:', error);
    throw new Error(error.message || 'Gagal mereset data perencanaan pernikahan.');
  }

  return (data as ResetPlanningResult) || { success: true };
}

