import { AdministrativeStage, AdministrativeTaskMetadata } from './types';
import { TaskPriority } from '../../types/checklist';
import { ReligiousTradition } from '../context';

export interface AdministrativeTaskTemplate {
  id: string;
  stage: AdministrativeStage;
  title: string;
  shortLabel: string;
  description: string;
  priority: TaskPriority;
  isUniversal: boolean;
  applicableTraditions: ReligiousTradition[] | 'universal';
  estimatedMinutes: number;
  metadata: AdministrativeTaskMetadata;
}

export function isTemplateApplicableToReligion(
  template: AdministrativeTaskTemplate,
  religion: ReligiousTradition = 'islam'
): boolean {
  if (template.applicableTraditions === 'universal') {
    return true;
  }
  if (Array.isArray(template.applicableTraditions)) {
    return template.applicableTraditions.includes(religion);
  }
  return false;
}

export const ADMINISTRATIVE_TEMPLATES: Record<string, AdministrativeTaskTemplate> = {
  // ── 1. DOKUMEN IDENTITAS & MEDIS PRIBADI ─────────────────────────────────────
  'adm-doc-ktp': {
    id: 'adm-doc-ktp',
    stage: 'documents',
    title: 'Siapkan KTP Asli & Fotokopi Calon Pengantin',
    shortLabel: 'KTP Calon Pengantin',
    description: 'Siapkan KTP asli dan fotokopi (calon suami & calon istri) untuk verifikasi identitas dan NIK Dukcapil.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf c',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk verifikasi NIK dan status kependudukan di Sistem Dukcapil Kemenag.',
      practicalTips: 'Pastikan NIK aktif dan ejaan nama pada KTP sama persis dengan Kartu Keluarga dan Akta Lahir.',
    },
  },
  'adm-doc-kk': {
    id: 'adm-doc-kk',
    stage: 'documents',
    title: 'Siapkan Kartu Keluarga (KK) Asli & Fotokopi',
    shortLabel: 'Kartu Keluarga (KK)',
    description: 'Siapkan KK asli dan fotokopi dari kedua calon pengantin untuk verifikasi susunan keluarga.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf d',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk memverifikasi data keluarga, nama orang tua, dan status domisili.',
      practicalTips: 'Jika ada pembaruan data keluarga terkini, gunakan lembar KK dengan barcode resmi Dukcapil.',
    },
  },
  'adm-doc-akta': {
    id: 'adm-doc-akta',
    stage: 'documents',
    title: 'Siapkan Akta Kelahiran / Surat Keterangan Kelahiran',
    shortLabel: 'Akta Kelahiran',
    description: 'Siapkan fotokopi Akta Kelahiran atau Surat Keterangan Kelahiran dari Desa/Kelurahan.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf b',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk bukti tanggal lahir, tempat lahir, dan nasab nama orang tua.',
      practicalTips: 'Beberapa KUA juga menerima ijazah terakhir sebagai dokumen pembanding jika akta kelahiran belum ada.',
    },
  },
  'adm-doc-foto': {
    id: 'adm-doc-foto',
    stage: 'documents',
    title: 'Siapkan Pas Foto Formal Calon Pengantin (Background Biru)',
    shortLabel: 'Pas Foto Latar Biru',
    description: 'Siapkan pas foto resmi berlatar belakang biru (cetak ukuran 2x3 dan 4x6 serta file softcopy digital).',
    priority: 'medium',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 45,
    metadata: {
      requirementLevel: 'LOCAL_SERVICE_PRACTICE',
      sourceType: 'KEMENAG',
      sourceReference: 'Standar Layanan SIMKAH & KUA Nasional',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Standar layanan umum KUA & SIMKAH. Foto akan tercetak pada Buku Nikah dan Kartu Nikah Digital.',
      practicalTips: 'Gunakan pakaian berkerah rapi (atau berhijab rapi bagi wanita) dengan pencahayaan terang.',
    },
  },
  'adm-doc-wali-saksi': {
    id: 'adm-doc-wali-saksi',
    stage: 'documents',
    title: 'Siapkan Fotokopi KTP Orang Tua / Wali & 2 Orang Saksi',
    shortLabel: 'KTP Wali & Saksi',
    description: 'Kumpulkan fotokopi identitas KTP ayah kandung/wali nikah dan 2 orang saksi akad nikah.',
    priority: 'medium',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'LOCAL_SERVICE_PRACTICE',
      sourceType: 'LOCAL_KUA',
      sourceReference: 'SOP Pemeriksaan Nikah KUA',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Dibutuhkan saat pemeriksaan nikah di KUA untuk mencatat data wali dan saksi dalam akta nikah.',
      practicalTips: 'Saksi nikah harus beragama Islam, laki-laki, dewasa, berakal sehat, dan hadir saat akad.',
    },
  },
  'adm-urus-kesehatan': {
    id: 'adm-urus-kesehatan',
    stage: 'documents',
    title: 'Lakukan Skrining Kesehatan Catin di Puskesmas / Faskes',
    shortLabel: 'Surat Keterangan Sehat',
    description: 'Lakukan pemeriksaan kesehatan calon pengantin di Puskesmas/Faskes untuk mendapatkan Surat Keterangan Sehat.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 90,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf e',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk memastikan kesiapan fisik calon pengantin sebelum pernikahan.',
      practicalTips: 'Ideal dilakukan 1–3 bulan sebelum nikah. Konfirmasi juga apakah faskes/lembaga mewajibkan sertifikat sehat.',
    },
  },

  // ── 2. PENGURUSAN KELURAHAN & KUA ASAL ──────────────────────────────────────
  'adm-urus-rt-rw': {
    id: 'adm-urus-rt-rw',
    stage: 'jurisdiction',
    title: 'Minta Surat Pengantar RT / RW di Lingkungan Domisili',
    shortLabel: 'Pengantar RT/RW',
    description: 'Minta surat pengantar nikah dari pengurus RT/RW domisili masing-masing calon pengantin.',
    priority: 'medium',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 45,
    metadata: {
      requirementLevel: 'LOCAL_SERVICE_PRACTICE',
      sourceType: 'LOCAL_KUA',
      sourceReference: 'SOP Pelayanan Kantor Desa/Kelurahan',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Syarat standar administrasi di kantor desa/kelurahan untuk menerbitkan Formulir Pengantar Nikah.',
      practicalTips: 'Bawa fotokopi KTP dan KK saat menemui ketua RT dan ketua RW.',
    },
  },
  'adm-urus-n1': {
    id: 'adm-urus-n1',
    stage: 'jurisdiction',
    title: 'Urus Surat Pengantar Nikah dari Kelurahan / Desa (Model N1)',
    shortLabel: 'Surat N1 Kelurahan',
    description: 'Bawa berkas ke Kantor Kelurahan/Desa domisili untuk diterbitkan Surat Pengantar Nikah resmi (Model N1).',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf a',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional sebagai dokumen pengantar resmi yang menyatakan status lajang/kelayakan menikah ke KUA.',
      practicalTips: 'Diurus oleh calon suami dan calon istri di kantor kelurahan/desa wilayah KTP masing-masing.',
    },
  },
  'adm-urus-rekomendasi-groom': {
    id: 'adm-urus-rekomendasi-groom',
    stage: 'jurisdiction',
    title: 'Urus Surat Rekomendasi Nikah di KUA Asal Calon Suami',
    shortLabel: 'Rekomendasi KUA Suami',
    description: 'Bawa Surat N1 ke KUA kecamatan asal calon suami untuk menerbitkan Surat Rekomendasi Numpang Nikah.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf f',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional jika calon suami melangsungkan akad di luar kecamatan domisili KTP-nya.',
      practicalTips: 'Surat rekomendasi ini nantinya wajib diserahkan ke KUA kecamatan tempat pelaksanaan akad.',
    },
  },
  'adm-urus-rekomendasi-bride': {
    id: 'adm-urus-rekomendasi-bride',
    stage: 'jurisdiction',
    title: 'Urus Surat Rekomendasi Nikah di KUA Asal Calon Istri',
    shortLabel: 'Rekomendasi KUA Istri',
    description: 'Bawa Surat N1 ke KUA kecamatan asal calon istri untuk menerbitkan Surat Rekomendasi Numpang Nikah.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf f',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional jika calon istri melangsungkan akad di luar kecamatan domisili KTP-nya.',
      practicalTips: 'Surat rekomendasi ini nantinya wajib diserahkan ke KUA kecamatan tempat pelaksanaan akad.',
    },
  },

  // ── 3. PENDAFTARAN SIMKAH & PEMBAYARAN PNBP ──────────────────────────────────
  'adm-daftar-kua': {
    id: 'adm-daftar-kua',
    stage: 'registration',
    title: 'Daftarkan Kehendak Nikah di KUA / SIMKAH Online',
    shortLabel: 'Daftar KUA / SIMKAH',
    description: 'Daftarkan pernikahan melalui aplikasi SIMKAH Kemenag atau langsung ke KUA tempat akad (paling lambat H-10 hari kerja).',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 3 & Pasal 4',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Batas resmi regulasi adalah 10 hari kerja sebelum akad. Jika kurang, wajib menyertakan surat dispensasi.',
      practicalTips: 'WedSiap merekomendasikan mendaftar pada H-30 hari agar kuota jadwal penghulu aman.',
    },
  },
  'adm-daftar-bayar-pnbp': {
    id: 'adm-daftar-bayar-pnbp',
    stage: 'registration',
    title: 'Bayar Tagihan Biaya Nikah PNBP Rp600.000 via SIMKAH',
    shortLabel: 'Bayar PNBP Rp600.000',
    description: 'Lakukan pembayaran biaya PNBP resmi Rp600.000 ke kas negara menggunakan kode billing MPN G3 dari SIMKAH.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PP No. 59 Tahun 2018; PMA No. 30 Tahun 2024 Pasal 16',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib untuk akad di luar kantor KUA atau di luar hari/jam kerja resmi. Disetor ke kas negara bukan tunai.',
      practicalTips: 'Dapat dibayar via ATM, M-Banking, Teller Bank persepsi, atau Kantor Pos sebelum masa billing habis.',
    },
  },
  'adm-daftar-tarif-nol': {
    id: 'adm-daftar-tarif-nol',
    stage: 'registration',
    title: 'Konfirmasi Jadwal Akad di Balai Nikah KUA (Biaya Rp0)',
    shortLabel: 'Akad di Balai KUA (Rp0)',
    description: 'Konfirmasi ketersediaan ruang balai nikah KUA pada hari dan jam kerja operasional resmi.',
    priority: 'medium',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PP No. 59 Tahun 2018 Pasal 5 ayat (1)',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Pencatatan nikah di dalam kantor KUA pada hari dan jam kerja resmi adalah Rp0 (Gratis).',
      practicalTips: 'Pastikan kapasitas ruang balai nikah mencukupi untuk keluarga inti yang hadir.',
    },
  },

  // ── 4. PEMERIKSAAN BERKAS & BIMBINGAN PERKAWINAN ─────────────────────────────
  'adm-periksa-rapak': {
    id: 'adm-periksa-rapak',
    stage: 'examination',
    title: 'Hadiri Pemeriksaan Nikah (Rapak) di KUA Bersama Wali',
    shortLabel: 'Pemeriksaan Berkas (Rapak)',
    description: 'Hadiri verifikasi berkas dan rukun nikah di KUA bersama calon pengantin dan wali nikah.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 11 & Pasal 12',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk mencocokkan data asli, persetujuan kedua mempelai, dan keabsahan wali nikah.',
      practicalTips: 'Bawa seluruh dokumen asli (KTP, KK, Akta Lahir) saat hadir ke KUA.',
    },
  },
  'adm-periksa-bimwin': {
    id: 'adm-periksa-bimwin',
    stage: 'examination',
    title: 'Ikuti Bimbingan Perkawinan (Bimwin) Calon Pengantin',
    shortLabel: 'Bimbingan Perkawinan (Bimwin)',
    description: 'Ikuti kursus bimbingan perkawinan yang diselenggarakan KUA/Kemenag untuk pembekalan keluarga sakinah.',
    priority: 'medium',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 120,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 13',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Program pembekalan resmi Kemenag. Metode pelaksanaan (tatap muka / mandiri) ditentukan oleh KUA.',
      practicalTips: 'Tanyakan jadwal kelas Bimwin kepada petugas KUA saat sesi pemeriksaan berkas.',
    },
  },

  // ── 5. KONDISI KHUSUS (CONDITIONAL REQUIREMENTS) ────────────────────────────
  'adm-spec-izin-ortu-groom': {
    id: 'adm-spec-izin-ortu-groom',
    stage: 'documents',
    title: 'Siapkan Surat Izin Orang Tua / Wali untuk Calon Suami',
    shortLabel: 'Izin Ortu Suami (<21 thn)',
    description: 'Siapkan surat izin tertulis dari orang tua/wali karena calon suami belum genap berusia 21 tahun saat akad/pemberkatan.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 45,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 1 Tahun 1974 Pasal 6 ayat (2); PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf h',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib hukum bagi calon pengantin berusia di bawah 21 tahun.',
      practicalTips: 'Format surat disediakan oleh kelurahan atau surat pernyataan orang tua bermeterai.',
    },
  },
  'adm-spec-izin-ortu-bride': {
    id: 'adm-spec-izin-ortu-bride',
    stage: 'documents',
    title: 'Siapkan Surat Izin Orang Tua / Wali untuk Calon Istri',
    shortLabel: 'Izin Ortu Istri (<21 thn)',
    description: 'Siapkan surat izin tertulis dari orang tua/wali karena calon istri belum genap berusia 21 tahun saat akad/pemberkatan.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 45,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 1 Tahun 1974 Pasal 6 ayat (2); PMA No. 30 Tahun 2024 Pasal 4 ayat (1) huruf h',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib hukum bagi calon pengantin berusia di bawah 21 tahun.',
      practicalTips: 'Format surat disediakan oleh kelurahan atau surat pernyataan orang tua bermeterai.',
    },
  },
  'adm-spec-dispensasi-groom': {
    id: 'adm-spec-dispensasi-groom',
    stage: 'documents',
    title: 'Dapatkan Penetapan Dispensasi Kawin Pengadilan Agama (Calon Suami)',
    shortLabel: 'Dispensasi PA Suami (<19 thn)',
    description: 'Ajukan dan peroleh penetapan izin dispensasi kawin dari Pengadilan Agama karena usia calon suami di bawah 19 tahun.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 180,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 16 Tahun 2019 Pasal 7 ayat (2); PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf a',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib hukum mutlak. Tanpa penetapan pengadilan, KUA dilarang mencatat pernikahan usia < 19 tahun.',
      practicalTips: 'Proses sidang di Pengadilan Agama memerlukan waktu beberapa pekan. Ajukan jauh hari sebelum pendaftaran KUA.',
    },
  },
  'adm-spec-dispensasi-bride': {
    id: 'adm-spec-dispensasi-bride',
    stage: 'documents',
    title: 'Dapatkan Penetapan Dispensasi Kawin Pengadilan Agama (Calon Istri)',
    shortLabel: 'Dispensasi PA Istri (<19 thn)',
    description: 'Ajukan dan peroleh penetapan izin dispensasi kawin dari Pengadilan Agama karena usia calon istri di bawah 19 tahun.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 180,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 16 Tahun 2019 Pasal 7 ayat (2); PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf a',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib hukum mutlak. Tanpa penetapan pengadilan, KUA dilarang mencatat pernikahan usia < 19 tahun.',
      practicalTips: 'Proses sidang di Pengadilan Agama memerlukan waktu beberapa pekan. Ajukan jauh hari sebelum pendaftaran KUA.',
    },
  },
  'adm-spec-cerai-hidup-groom': {
    id: 'adm-spec-cerai-hidup-groom',
    stage: 'documents',
    title: 'Siapkan Kutipan Akta Cerai Asli Pengadilan Agama (Calon Suami)',
    shortLabel: 'Akta Cerai Suami',
    description: 'Siapkan Akta Cerai asli yang telah berkekuatan hukum tetap (Inkracht) dari Pengadilan Agama.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf d',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk membuktikan status perkawinan terdahulu telah putus secara hukum.',
      practicalTips: 'Pastikan membawa kutipan akta cerai asli, bukan hanya salinan putusan pengadilan.',
    },
  },
  'adm-spec-cerai-hidup-bride': {
    id: 'adm-spec-cerai-hidup-bride',
    stage: 'documents',
    title: 'Siapkan Kutipan Akta Cerai Asli Pengadilan Agama (Calon Istri)',
    shortLabel: 'Akta Cerai Istri',
    description: 'Siapkan Akta Cerai asli dari Pengadilan Agama dan pastikan masa iddah telah terlewati.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf d',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk membuktikan status janda cerai dan pemenuhan masa iddah.',
      practicalTips: 'KUA akan memeriksa tanggal putusan dan perhitungan selesainya masa iddah.',
    },
  },
  'adm-spec-cerai-mati-groom': {
    id: 'adm-spec-cerai-mati-groom',
    stage: 'documents',
    title: 'Siapkan Akta Kematian Pasangan / Surat Model N6 (Calon Suami)',
    shortLabel: 'Akta Kematian Istri Terdahulu',
    description: 'Siapkan Akta Kematian dari Disdukcapil atau Surat Keterangan Kematian (Model N6) dari kelurahan.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf e',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional sebagai bukti sah status duda mati.',
      practicalTips: 'Jika Akta Kematian Disdukcapil belum terbit, gunakan Surat Keterangan Kematian Kelurahan.',
    },
  },
  'adm-spec-cerai-mati-bride': {
    id: 'adm-spec-cerai-mati-bride',
    stage: 'documents',
    title: 'Siapkan Akta Kematian Pasangan / Surat Model N6 (Calon Istri)',
    shortLabel: 'Akta Kematian Suami Terdahulu',
    description: 'Siapkan Akta Kematian dari Disdukcapil atau Surat Keterangan Kematian dari kelurahan.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 30,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf e',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional untuk verifikasi status janda mati.',
      practicalTips: 'Bawa kutipan Akta Kematian resmi dari Disdukcapil atau surat keterangan kelurahan.',
    },
  },
  'adm-spec-tni-polri-groom': {
    id: 'adm-spec-tni-polri-groom',
    stage: 'documents',
    title: 'Urus Surat Izin Menikah dari Komandan / Atasan Kesatuan (Calon Suami)',
    shortLabel: 'Izin Komandan TNI/Polri Suami',
    description: 'Urus izin dinas pernikahan resmi dari kesatuan TNI/POLRI bagi calon suami.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 120,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf b; Peraturan Panglima TNI / Kapolri',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib regulasi kedinasan militer/kepolisian dan syarat mutlak pendaftaran perkawinan resmi.',
      practicalTips: 'Proses administrasi internal kesatuan (sidang nikah dinas/kantor) harus diselesaikan terlebih dahulu.',
    },
  },
  'adm-spec-tni-polri-bride': {
    id: 'adm-spec-tni-polri-bride',
    stage: 'documents',
    title: 'Urus Surat Izin Menikah dari Komandan / Atasan Kesatuan (Calon Istri)',
    shortLabel: 'Izin Komandan TNI/Polri Istri',
    description: 'Urus izin dinas pernikahan resmi dari kesatuan TNI/POLRI bagi calon istri.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 120,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf b; Peraturan Panglima TNI / Kapolri',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib regulasi kedinasan militer/kepolisian dan syarat mutlak pendaftaran perkawinan resmi.',
      practicalTips: 'Proses administrasi internal kesatuan (sidang nikah dinas/kantor) harus diselesaikan terlebih dahulu.',
    },
  },
  'adm-spec-wna-groom': {
    id: 'adm-spec-wna-groom',
    stage: 'documents',
    title: 'Siapkan Dokumen Izin Kedutaan & Paspor Sah (Calon Suami WNA)',
    shortLabel: 'Izin Kedutaan & Paspor WNA',
    description: 'Siapkan Surat Izin Menikah dari Kedutaan Asal (CNI), legalisasi paspor, dan visa/izin tinggal.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 120,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 1 Tahun 1974 Pasal 56–62; Permendagri / PMA',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional bagi pernikahan campuran beda kewarganegaraan.',
      practicalTips: 'Dokumen berbahasa asing wajib diterjemahkan oleh Penerjemah Tersumpah (Sworn Translator).',
    },
  },
  'adm-spec-wna-bride': {
    id: 'adm-spec-wna-bride',
    stage: 'documents',
    title: 'Siapkan Dokumen Izin Kedutaan & Paspor Sah (Calon Istri WNA)',
    shortLabel: 'Izin Kedutaan & Paspor WNA',
    description: 'Siapkan Surat Izin Menikah dari Kedutaan Asal (CNI), legalisasi paspor, dan visa/izin tinggal.',
    priority: 'high',
    isUniversal: true,
    applicableTraditions: 'universal',
    estimatedMinutes: 120,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 1 Tahun 1974 Pasal 56–62; Permendagri / PMA',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib nasional bagi pernikahan campuran beda kewarganegaraan.',
      practicalTips: 'Dokumen berbahasa asing wajib diterjemahkan oleh Penerjemah Tersumpah (Sworn Translator).',
    },
  },
  'adm-spec-poligami': {
    id: 'adm-spec-poligami',
    stage: 'documents',
    title: 'Dapatkan Penetapan Izin Poligami dari Pengadilan Agama',
    shortLabel: 'Izin Poligami Pengadilan Agama',
    description: 'Ajukan dan peroleh penetapan izin beristri lebih dari satu dari Pengadilan Agama yang telah berkekuatan hukum tetap.',
    priority: 'high',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 180,
    metadata: {
      requirementLevel: 'NATIONAL_REQUIREMENT',
      sourceType: 'REGULATION',
      sourceReference: 'UU No. 1 Tahun 1974 Pasal 3–5; PMA No. 30 Tahun 2024 Pasal 4 ayat (2) huruf c',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Wajib hukum mutlak bagi suami yang hendak menikah kembali saat masih terikat perkawinan sah.',
      practicalTips: 'Sidang permohonan poligami memerlukan persetujuan istri terdahulu dan bukti kepastian kemampuan nafkah.',
    },
  },
  'adm-spec-wali-hakim': {
    id: 'adm-spec-wali-hakim',
    stage: 'jurisdiction',
    title: 'Konfirmasi Penetapan Wali Hakim ke KUA',
    shortLabel: 'Penetapan Wali Hakim',
    description: 'Konsultasikan penetapan Kepala KUA sebagai Wali Hakim karena tidak adanya wali nasab yang memenuhi syarat fiqih.',
    priority: 'medium',
    isUniversal: false,
    applicableTraditions: ['islam'],
    estimatedMinutes: 60,
    metadata: {
      requirementLevel: 'CONFIRM_WITH_KUA',
      sourceType: 'LOCAL_KUA',
      sourceReference: 'PMA No. 30 Tahun 2024 Pasal 12 ayat (4)',
      lastVerifiedAt: '2025-01-15',
      explanation: 'Kepala KUA bertindak sebagai wali hakim jika calon mempelai wanita tidak memiliki wali nasab yang sah.',
      practicalTips: 'Bawa surat keterangan kematian ayah atau surat keterangan silsilah keluarga dari kelurahan.',
    },
  },
};
